services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: unless-stopped
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    command:
      - "--providers.file.filename=/traefik.yaml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik/traefik.yaml:/traefik.yaml"
      - "./traefik/dynamic_conf.yaml:/etc/traefik/dynamic_conf.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  mosquitto:
  postgres:
