services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: postgres
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  mqtt:
  postgres:
